In [90]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm

In [91]:
df=pd.read_csv('../dataset/diabetes.csv')

In [92]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [93]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [94]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [95]:
df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [96]:
x=df.drop(columns='Outcome',axis=1)
y=df['Outcome']

In [97]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [100]:
ytest.shape

(154,)

In [101]:
classifier=svm.SVC(kernel='linear')

In [102]:
classifier.fit(xtrain,ytrain)

SVC(kernel='linear')

In [103]:
predictor=classifier.predict(xtest)

In [104]:
from sklearn.metrics import accuracy_score

In [105]:
print('Accuracy score of the training data:',accuracy_score(predictor,ytest))

Accuracy score of the training data: 0.7207792207792207


In [118]:
input_data = (6,167,76,30,170,24.6,0.567,41)
input_array=np.array(input_data)
input_array

array([  6.   , 167.   ,  76.   ,  30.   , 170.   ,  24.6  ,   0.567,
        41.   ])

In [119]:
input_reshaped=input_array.reshape(1,-1)
input_reshaped

array([[  6.   , 167.   ,  76.   ,  30.   , 170.   ,  24.6  ,   0.567,
         41.   ]])

In [120]:
classifier.predict(input_reshaped)

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [121]:
if (predictor[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

The person is diabetic


In [123]:
import pickle

In [124]:
filename = 'classifier.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [126]:
Model= pickle.load(open('classifier.sav', 'rb'))